export type ReportField = { key: string; label: string };

export type ReportConversation = {
  title: string;
  createdAt?: string;
  messages: { from: string; body: string; at?: string }[];
};

export type ReportInput = {
  fields: Record<string, string>;
  fieldDefs: ReportField[];
  createdAt?: string;
  attachments?: { name: string; type?: string; size?: number }[];
  hasAudio?: boolean;
  conversations?: ReportConversation[];
  /** List fields with no answer as "Not provided" so shared reports read as complete. */
  includeEmptyFields?: boolean;
};

function formatSize(bytes?: number) {
  if (!bytes || bytes <= 0) return "";
  const kb = bytes / 1024;
  return kb < 1024 ? ` (${Math.round(kb)} KB)` : ` (${(kb / 1024).toFixed(1)} MB)`;
}

export function buildReportText({
  fields,
  fieldDefs,
  createdAt,
  attachments = [],
  hasAudio = false,
  conversations = [],
  includeEmptyFields = true,
}: ReportInput) {
  const lines: string[] = [];
  const recorded = new Date(createdAt ?? Date.now());
  lines.push("INCIDENT REPORT");
  lines.push(`Recorded: ${recorded.toLocaleString()}`);
  lines.push(`Report generated: ${new Date().toLocaleString()}`);
  lines.push(`Time zone: ${Intl.DateTimeFormat().resolvedOptions().timeZone ?? "unknown"}`);
  lines.push("");
  lines.push("DETAILS");

  const answered = fieldDefs.filter((f) => (fields?.[f.key] ?? "").trim());
  for (const f of fieldDefs) {
    const v = (fields?.[f.key] ?? "").trim();
    if (v) {
      lines.push(`${f.label}: ${v}`);
    } else if (includeEmptyFields) {
      lines.push(`${f.label}: Not provided`);
    }
  }
  if (answered.length === 0) lines.push("(No written details were entered for this report.)");

  lines.push("");
  lines.push("EVIDENCE");
  if (attachments.length > 0) {
    lines.push(`Attachments (${attachments.length}):`);
    for (const a of attachments) {
      lines.push(`  • ${a.name}${a.type ? ` — ${a.type}` : ""}${formatSize(a.size)}`);
    }
  } else {
    lines.push("Attachments: none");
  }
  lines.push(hasAudio ? "Voice note: yes (attached in app)" : "Voice note: none");

  lines.push("");
  if (conversations.length > 0) {
    const total = conversations.reduce((n, c) => n + c.messages.length, 0);
    lines.push(`SAVED CONVERSATIONS (${conversations.length}, ${total} messages)`);
    for (const c of conversations) {
      lines.push("");
      lines.push(`— ${c.title}${c.createdAt ? ` (${new Date(c.createdAt).toLocaleString()})` : ""}`);
      for (const m of c.messages) {
        const stamp = m.at ? ` [${new Date(m.at).toLocaleString()}]` : "";
        lines.push(`${m.from}${stamp}: ${m.body}`);
      }
    }
  } else {
    lines.push("SAVED CONVERSATIONS: none included");
  }
  lines.push("");
  lines.push("Generated by MrsANONymous.org");
  return lines.join("\n");
}


export function reportFileName(createdAt?: string) {
  const d = new Date(createdAt ?? Date.now());
  const pad = (n: number) => String(n).padStart(2, "0");
  return `incident-report-${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}.txt`;
}

export function downloadReport(text: string, createdAt?: string) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = reportFileName(createdAt);
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

/** Share the report as a real file when the device supports it, else share text, else download. */
export async function shareReport(text: string, createdAt?: string): Promise<string> {
  const name = reportFileName(createdAt);
  try {
    const file = new File([text], name, { type: "text/plain" });
    const nav = navigator as Navigator & {
      canShare?: (d: ShareData) => boolean;
      share?: (d: ShareData) => Promise<void>;
    };
    if (nav.share && nav.canShare?.({ files: [file] })) {
      await nav.share({ files: [file], title: "Incident report" });
      return "Shared.";
    }
    if (nav.share) {
      await nav.share({ title: "Incident report", text });
      return "Shared.";
    }
  } catch (err) {
    if ((err as Error)?.name === "AbortError") return "";
  }
  downloadReport(text, createdAt);
  return "Sharing isn't supported here — the report was downloaded instead.";
}

/** SMS bodies must stay short; trim to a safe length for emergency texting. */
export function printReport(text: string) {
  const w = window.open("", "_blank", "noopener,width=800,height=900");
  if (!w) return "Pop-ups are blocked, so the report couldn't be printed.";
  const esc = text.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] as string);
  w.document.write(
    `<html><head><title>Incident report</title></head><body style="font:14px/1.5 system-ui;padding:32px"><pre style="white-space:pre-wrap;font:inherit">${esc}</pre></body></html>`,
  );
  w.document.close();
  w.focus();
  w.print();
  return "";
}

export function smsReportHref(number: string, text: string, limit = 900) {
  const body = text.length > limit ? `${text.slice(0, limit - 3)}...` : text;
  return `sms:${number}?&body=${encodeURIComponent(body)}`;
}
