export type ReportField = { key: string; label: string };

export type ReportConversation = {
  title: string;
  createdAt?: string;
  messages: { from: string; body: string; at?: string }[];
};

export type ReportInput = {
  fields: Record<string, string>;
  fieldDefs: ReportField[];
  createdAt?: string;
  attachments?: { name: string }[];
  hasAudio?: boolean;
  conversations?: ReportConversation[];
};

export function buildReportText({
  fields,
  fieldDefs,
  createdAt,
  attachments = [],
  hasAudio = false,
  conversations = [],
}: ReportInput) {
  const lines: string[] = [];
  lines.push("INCIDENT REPORT");
  lines.push(`Recorded: ${new Date(createdAt ?? Date.now()).toLocaleString()}`);
  lines.push("");
  for (const f of fieldDefs) {
    const v = (fields?.[f.key] ?? "").trim();
    if (v) lines.push(`${f.label}: ${v}`);
  }
  if (attachments.length > 0) {
    lines.push("");
    lines.push(`Attachments: ${attachments.map((a) => a.name).join(", ")}`);
  }
  if (hasAudio) lines.push("Voice note: attached in app");
  if (conversations.length > 0) {
    lines.push("");
    lines.push("SAVED CONVERSATIONS");
    for (const c of conversations) {
      lines.push("");
      lines.push(`— ${c.title}${c.createdAt ? ` (${new Date(c.createdAt).toLocaleString()})` : ""}`);
      for (const m of c.messages) {
        const stamp = m.at ? ` [${new Date(m.at).toLocaleString()}]` : "";
        lines.push(`${m.from}${stamp}: ${m.body}`);
      }
    }
  }
  lines.push("");
  lines.push("Generated by MrsANONymous.org");
  return lines.join("\n");
}

export function reportFileName(createdAt?: string) {
  const d = new Date(createdAt ?? Date.now());
  const pad = (n: number) => String(n).padStart(2, "0");
  return `incident-report-${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}.txt`;
}

export function downloadReport(text: string, createdAt?: string) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = reportFileName(createdAt);
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

/** Share the report as a real file when the device supports it, else share text, else download. */
export async function shareReport(text: string, createdAt?: string): Promise<string> {
  const name = reportFileName(createdAt);
  try {
    const file = new File([text], name, { type: "text/plain" });
    const nav = navigator as Navigator & {
      canShare?: (d: ShareData) => boolean;
      share?: (d: ShareData) => Promise<void>;
    };
    if (nav.share && nav.canShare?.({ files: [file] })) {
      await nav.share({ files: [file], title: "Incident report" });
      return "Shared.";
    }
    if (nav.share) {
      await nav.share({ title: "Incident report", text });
      return "Shared.";
    }
  } catch (err) {
    if ((err as Error)?.name === "AbortError") return "";
  }
  downloadReport(text, createdAt);
  return "Sharing isn't supported here — the report was downloaded instead.";
}

/** SMS bodies must stay short; trim to a safe length for emergency texting. */
export function printReport(text: string) {
  const w = window.open("", "_blank", "noopener,width=800,height=900");
  if (!w) return "Pop-ups are blocked, so the report couldn't be printed.";
  const esc = text.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] as string);
  w.document.write(
    `<html><head><title>Incident report</title></head><body style="font:14px/1.5 system-ui;padding:32px"><pre style="white-space:pre-wrap;font:inherit">${esc}</pre></body></html>`,
  );
  w.document.close();
  w.focus();
  w.print();
  return "";
}

export function smsReportHref(number: string, text: string, limit = 900) {
  const body = text.length > limit ? `${text.slice(0, limit - 3)}...` : text;
  return `sms:${number}?&body=${encodeURIComponent(body)}`;
}
