/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TellYourStoryRouteImport } from './routes/tell-your-story'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityQuestionsRouteImport } from './routes/security-questions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GirlsRouteImport } from './routes/girls'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebooksIdRouteImport } from './routes/notebooks.$id'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TellYourStoryRoute = TellYourStoryRouteImport.update({
  id: '/tell-your-story',
  path: '/tell-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityQuestionsRoute = SecurityQuestionsRouteImport.update({
  id: '/security-questions',
  path: '/security-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GirlsRoute = GirlsRouteImport.update({
  id: '/girls',
  path: '/girls',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIdRoute = NotebooksIdRouteImport.update({
  id: '/notebooks/$id',
  path: '/notebooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/girls': typeof GirlsRoute
  '/inbox': typeof InboxRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/women': typeof WomenRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/girls': typeof GirlsRoute
  '/inbox': typeof InboxRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/women': typeof WomenRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/girls': typeof GirlsRoute
  '/inbox': typeof InboxRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/women': typeof WomenRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/girls'
    | '/inbox'
    | '/journal'
    | '/login'
    | '/privacy'
    | '/resources'
    | '/security-questions'
    | '/settings'
    | '/signup'
    | '/tell-your-story'
    | '/terms'
    | '/tools'
    | '/women'
    | '/admin/messages'
    | '/admin/moderation'
    | '/notebooks/$id'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/girls'
    | '/inbox'
    | '/journal'
    | '/login'
    | '/privacy'
    | '/resources'
    | '/security-questions'
    | '/settings'
    | '/signup'
    | '/tell-your-story'
    | '/terms'
    | '/tools'
    | '/women'
    | '/admin/messages'
    | '/admin/moderation'
    | '/notebooks/$id'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/girls'
    | '/inbox'
    | '/journal'
    | '/login'
    | '/privacy'
    | '/resources'
    | '/security-questions'
    | '/settings'
    | '/signup'
    | '/tell-your-story'
    | '/terms'
    | '/tools'
    | '/women'
    | '/admin/messages'
    | '/admin/moderation'
    | '/notebooks/$id'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardRoute: typeof BoardRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GirlsRoute: typeof GirlsRoute
  InboxRoute: typeof InboxRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityQuestionsRoute: typeof SecurityQuestionsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TellYourStoryRoute: typeof TellYourStoryRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  WomenRoute: typeof WomenRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  NotebooksIdRoute: typeof NotebooksIdRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tell-your-story': {
      id: '/tell-your-story'
      path: '/tell-your-story'
      fullPath: '/tell-your-story'
      preLoaderRoute: typeof TellYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-questions': {
      id: '/security-questions'
      path: '/security-questions'
      fullPath: '/security-questions'
      preLoaderRoute: typeof SecurityQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/girls': {
      id: '/girls'
      path: '/girls'
      fullPath: '/girls'
      preLoaderRoute: typeof GirlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$id': {
      id: '/notebooks/$id'
      path: '/notebooks/$id'
      fullPath: '/notebooks/$id'
      preLoaderRoute: typeof NotebooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardRoute: BoardRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GirlsRoute: GirlsRoute,
  InboxRoute: InboxRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityQuestionsRoute: SecurityQuestionsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TellYourStoryRoute: TellYourStoryRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  WomenRoute: WomenRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminModerationRoute: AdminModerationRoute,
  NotebooksIdRoute: NotebooksIdRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
