/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TellYourStoryRouteImport } from './routes/tell-your-story'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityQuestionsRouteImport } from './routes/security-questions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GirlsRouteImport } from './routes/girls'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebooksIdRouteImport } from './routes/notebooks.$id'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TellYourStoryRoute = TellYourStoryRouteImport.update({
  id: '/tell-your-story',
  path: '/tell-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityQuestionsRoute = SecurityQuestionsRouteImport.update({
  id: '/security-questions',
  path: '/security-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GirlsRoute = GirlsRouteImport.update({
  id: '/girls',
  path: '/girls',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIdRoute = NotebooksIdRouteImport.update({
  id: '/notebooks/$id',
  path: '/notebooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/girls': typeof GirlsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/signup': typeof SignupRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/tools': typeof ToolsRoute
  '/women': typeof WomenRoute
  '/notebooks/$id': typeof NotebooksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/girls': typeof GirlsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/signup': typeof SignupRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/tools': typeof ToolsRoute
  '/women': typeof WomenRoute
  '/notebooks/$id': typeof NotebooksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/girls': typeof GirlsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/signup': typeof SignupRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/tools': typeof ToolsRoute
  '/women': typeof WomenRoute
  '/notebooks/$id': typeof NotebooksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board'
    | '/contact'
    | '/forgot-password'
    | '/girls'
    | '/inbox'
    | '/login'
    | '/resources'
    | '/security-questions'
    | '/signup'
    | '/tell-your-story'
    | '/tools'
    | '/women'
    | '/notebooks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board'
    | '/contact'
    | '/forgot-password'
    | '/girls'
    | '/inbox'
    | '/login'
    | '/resources'
    | '/security-questions'
    | '/signup'
    | '/tell-your-story'
    | '/tools'
    | '/women'
    | '/notebooks/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board'
    | '/contact'
    | '/forgot-password'
    | '/girls'
    | '/inbox'
    | '/login'
    | '/resources'
    | '/security-questions'
    | '/signup'
    | '/tell-your-story'
    | '/tools'
    | '/women'
    | '/notebooks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardRoute: typeof BoardRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GirlsRoute: typeof GirlsRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityQuestionsRoute: typeof SecurityQuestionsRoute
  SignupRoute: typeof SignupRoute
  TellYourStoryRoute: typeof TellYourStoryRoute
  ToolsRoute: typeof ToolsRoute
  WomenRoute: typeof WomenRoute
  NotebooksIdRoute: typeof NotebooksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tell-your-story': {
      id: '/tell-your-story'
      path: '/tell-your-story'
      fullPath: '/tell-your-story'
      preLoaderRoute: typeof TellYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-questions': {
      id: '/security-questions'
      path: '/security-questions'
      fullPath: '/security-questions'
      preLoaderRoute: typeof SecurityQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/girls': {
      id: '/girls'
      path: '/girls'
      fullPath: '/girls'
      preLoaderRoute: typeof GirlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$id': {
      id: '/notebooks/$id'
      path: '/notebooks/$id'
      fullPath: '/notebooks/$id'
      preLoaderRoute: typeof NotebooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardRoute: BoardRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GirlsRoute: GirlsRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityQuestionsRoute: SecurityQuestionsRoute,
  SignupRoute: SignupRoute,
  TellYourStoryRoute: TellYourStoryRoute,
  ToolsRoute: ToolsRoute,
  WomenRoute: WomenRoute,
  NotebooksIdRoute: NotebooksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
